### ISSUE TITLE
AdView shows up on OnResume() & onPause()

### ISSUE THREAD

**Issue by ItzNotABug** [tslamic/premiumer#11]
I checked the Sample App & found an issue where if the Billing is successfull, then the AdView's Visibility is set to Gone...
But if you try pressing the Back button or the Recent apps or Open the App again after an Exit then the AdView is visible for some seconds...
Any workaround or suggestions?

By the way, Thanks for the Great Library 😀
Simple & Hassle free 😀

**Comment by tslamic** [comment]
Hi @Darshan10298, thanks for reporting this. I'll have a look once I have some spare time - hopefully later today or tomorrow.

**Comment by ItzNotABug** [comment]
@tslamic Okay  😀

**Comment by ItzNotABug** [comment]
@tslamic
did you check?

**Comment by dejiapps** [comment]
I have this issue too. Basically when an activity is open onShowAds() always gets called which shows the ad for a second before onHideAds() is called. It would be nice if onHideAds() is called first, and then if that is false, onShowAds() should then be called.

**Comment by ItzNotABug** [comment]
@dejiapps
I haven't tried this but may be it can be helpfull...
Keep the initial visibility of the AdView as Gone then alter it onShowAds & onHideAds ... :)

UPDATE:
The method above doesn't work!

**Comment by tslamic** [comment]
@dejiapps @Darshan10298 I'm very sorry, struggling to find time to address this. In spirits of open source, if you guys have a broad idea on how this should be fixed, could you please create a PR? Many thanks and sorry again.

**Comment by tslamic** [comment]
@dejiapps @Darshan10298 a potential fix has been pushed to branch `issue#11`. Could you please check if it solves this issue?
If not, I'll need detailed reproduction steps to tackle this further.

**Comment by Darshan10298** [comment]
@tslamic
I tried the issue#11 branch's sample...
The Issue remained...

But,
I found a workaround, don't know if its a good thing (maybe it is :P)

The problem was in the onPause() & onResume(), I guess...
I moved the premiumer.bind(); from onResume() to onCreate() & premiumer.unbind(); from onPause() to onDestroy();

Guess what?
Works for now... :)
It solves the issue where the AdView is visible for a fraction of Seconds...

**Comment by ItzNotABug** [comment]
I tried the issue#11 branch's sample...
The Issue remained... :(

**Comment by tslamic** [comment]
As no repro steps have been provided, I'm closing this issue due to inactivity. @Darshan10298 @dejiapps feel free to reopen/report a new issue with clear repro steps.
